version: '3.5'

services:

  provisioning-app:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:5000'
    environment:
      - NODE_ENV=production